apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portals.fullname" . }}
  labels:
    {{- include "portals.labels" . | nindent 4 }}
{{- with .Values.environment }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
