apiVersion: v1
kind: Service
metadata:
  name: {{ include "portals.fullname" . }}
  labels:
    {{- include "portals.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "portals.selectorLabels" . | nindent 4 }}
